### PR TITLE
Updated grid ratio

### PR DESCRIPTION
**Pull request by rjderosa**
Modified the apodizer specification file with updated grid ratios and new second-order ratios. Pipeline should now read the SATSORDR keyword to determine which were used.

### CODE REVIEW

**Review by semaphoreP — APPROVED** [review]

**Comment by mperrin** [comment]
Thanks @rjderosa!

**Comment by mperrin** [comment]
The PR looks good. But since you're updating the satellite spot grid ratios, should we add some brief citation/source information on where those new values come from? Could be just some additional comments in that file. Would be good to have that source information recorded for reference.

**Comment by rjderosa** [comment]
We can add a URL to the gemini website once I send them the report and they upload it.

**Comment by mperrin** [comment]
Any idea when that will be? Do you want me to go ahead and merge this now (in which case we have to remember to come back later and add the URL), or leave this PR open and pending until they tell you the URL? Either way's fine with me

**Comment by rjderosa** [comment]
Hopefully soon, just waiting to hear back from Vanessa. Let's wait until we can add the URL.

**Comment by semaphoreP** [comment]
If it is longer than 1-2 weeks, let's merge this branch and make a new issue to add the reference when it appears. Just so that these changes get propagated.

**Comment by rjderosa** [comment]
Hopefully should get a link to the gemini instrument page in a couple of days that we can add to finalise this.

**Comment by rjderosa** [comment]
Which has now been added. The branch can now be merged. Should we release this as 1.4.1?

**Comment by mperrin** [comment]
Let's have a discussion about release at an upcoming data telecon?

**Comment by semaphoreP** [comment]
@mperrin should we merge this into master? I think we should do that irrespective of a release, but I also think a release is a good idea.

**Comment by rjderosa** [comment]
Shall we merge this?

**Pull request merged**
